#!/usr/bin/env bash
# Configuring HAProxy

apt-get -y update
apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.0

apt-get install -y haproxy=2.0.\*

echo "
frontend lbnb.tech
        bind 0:80
        default_backend lbnb.tech_backend
backend lbnb.tech_backend
        balance roundrobin
        server 295713-web-01 100.26.151.120:80
        server 295713-web-02 54.144.84.215:80
" >> /etc/haproxy/haproxy.cfg

service haproxy restart
